### ISSUE TITLE
Bug: Deletion target wrong items when on summary screen

### ISSUE THREAD

**Issue by clement0010** [AY2122S2-CS2103T-T11-1/tp#114]
Note: Patient's attributes are defined as contact, medical, consultation, test and prescription.

There are two bugs here:

## Wrong entry deletion
When a user is on the summary page, deletion will delete the entry from the last visited screen attributes.
To reproduce
1. `add i/S1234567L t/contact n/John Smith p/88888888 e/johns@example.com a/21 Lower Kent Ridge Road, Singapore 119077 ` to add a contact number to `S1234567L`
2. `view i/S1234567L` to view summary
3. `delete 1` delete contact

Intended outcome:
1. User deletes the current patient instead of contact.

## Redirect upon deletion
Upon deleting the last entry from the patient's attributes, redirect to the default screen shows the target patient instead of all patients.
1. `view i/S1234567L` to view summary
2. `add i/S1234567L t/prescription n/Acetaminophen dt/2022-02-22 s/2 tablets after meal everyday ` to add a prescription to `S1234567L`
3. `delete 1` delete Acetaminophen prescription and redirect to a patient screen showing the deleted prescription owner.

Intended outcome:
1. User deletes the prescription and redirects to the patient screen showing the **full list** of patients.

## Possible causes of the bug:
1. Global state is not well maintained
2. Implementation of new features does not account for integration with other features

## Resolution
1. Streamline the deletion logic. Always delete what is on the screen **ONLY**
2. Manual testing on local is required before approving the PR
3. `delete`, `find` features must be tested thoroughly as these functions encapsulate all other patient attributes

**Comment by juslam19** [comment]
Has this already been resolved? Seems so on my end.

**Comment by clement0010** [comment]
> 2\. view i/S1234567L

Nope. Do a clean reset before trying it

**Comment by clement0010** [comment]
> Has this already been resolved? Seems so on my end. It doesn't seem to be happening when I copy-paste the commands listed above.

Nope. Do a clean reset before trying it

**Comment by sibinhho99-nus** [comment]
> > Has this already been resolved? Seems so on my end. It doesn't seem to be happening when I copy-paste the commands listed above.
> 
> Nope. Do a clean reset before trying it

Yup will fix

**Comment by clement0010** [comment]
> > > Has this already been resolved? Seems so on my end. It doesn't seem to be happening when I copy-paste the commands listed above.
> > 
> > 
> > Nope. Do a clean reset before trying it
> 
> Yup will fix

Can u do it along with the summary screen enhancement

**Comment by sibinhho99-nus** [comment]
> > > > Has this already been resolved? Seems so on my end. It doesn't seem to be happening when I copy-paste the commands listed above.
> > > 
> > > 
> > > Nope. Do a clean reset before trying it
> > 
> > 
> > Yup will fix
> 
> Can u do it along with the summary screen enhancement

What alternative do you have in mind?

**Comment by clement0010** [comment]
> > > > > Has this already been resolved? Seems so on my end. It doesn't seem to be happening when I copy-paste the commands listed above.
> > > > 
> > > > 
> > > > Nope. Do a clean reset before trying it
> > > 
> > > 
> > > Yup will fix
> > 
> > 
> > Can u do it along with the summary screen enhancement
> 
> What alternative do you have in mind? Some more specific descriptions would be useful

You can use a VBox to stack the stack pane vertically.

![image](https://user-images.githubusercontent.com/56408987/160751604-a5215140-184f-439b-b5f8-241485632134.png)

Anyways lets bring this to #111 if you wanna continue the discussion
