### ISSUE TITLE
FindMedical Bug: `find nil` returns result

### ISSUE THREAD

**Issue by joey-chance** [AY2122S2-CS2103T-T11-1/tp#117]
Since medical details can be empty, `find nil` actually returns a result.

**Comment by clement0010** [comment]
Using `find` in the `summary` screen causes a UI bug too.

To replicate:
1. `view t/contact i/S1234567L` to view contact
2. `view i/S1234567L` to view summary
3. `find` finds keyword in contact

Possible cause: Integration issue between `find` and `view` summary

CC: @sibinhho99-nus

**Comment by sibinhho99-nus** [comment]
> @sibinhho99-nus Just disable `find` in medical since this feature only has at most one entry

Ok, will do

**Comment by sibinhho99-nus** [comment]
> @sibinhho99-nus Just disable `find` in medical since this feature only has at most one entry

@clement0010 I relooked at it. It's for find after `view t/medical` (with no NRIC specified) which lists all medical information, so find should still work

**Comment by sibinhho99-nus** [comment]
![photo_2022-04-01 19 55 16](https://user-images.githubusercontent.com/97666199/161258604-ddaea786-62f6-4491-9d47-97e6468a5121.jpeg)
