### ISSUE TITLE
UI Bug: Blank screen upon deleting the last entry.

### ISSUE THREAD

**Issue by clement0010** [AY2122S2-CS2103T-T11-1/tp#118]
The user is shown an empty panel after deleting the last entry. To replicate:

Pre-requisite
1. Clean reset MedBook before replicating the bug.

### Consultation
1. `add i/S1234569L t/consultation dt/19-09-2020 tm/19-00 dg/Upper respiratory infection. Patient was having cough, sneezing fits. fe/54.00 nt/Should get more cough drops.`
2. `delete 1` to delete the last entry in the current view

UI Bug:
![image](https://user-images.githubusercontent.com/56408987/160752122-5bab1431-6594-46df-8029-bef2e1f01033.png)

Intended Result:
1. Redirect the user to the default screen instead of showing a blank panel. Refer to #65 to see how it was implemented.

### Medical
1. `add i/S1234569L t/medical`
2. `delete 1` to delete the last entry in the current view

UI Bug:
![image](https://user-images.githubusercontent.com/56408987/160752622-07c019cd-81f6-4608-aa31-cbb5de6800ba.png)

Intended Result:
1. Redirect the user to the default screen instead of showing a blank panel. Refer to #65 to see how it was implemented.

**Comment by cheekean5848** [comment]
Ya, I agree this should be the right way

**Comment by cheekean5848** [comment]
Let me take it

**Comment by sibinhho99-nus** [comment]
> Let me take it

Ok tks
