### ISSUE TITLE
Polish UI messages in password

### ISSUE THREAD

**Issue by sibinhho99-nus** [AY2122S2-CS2103T-T11-1/tp#120]
(Can leave to v1.4)

<img width="433" alt="Screenshot 2022-03-30 at 2 17 57 PM" src="https://user-images.githubusercontent.com/97666199/160764180-d42da787-dd92-4573-9130-41950688d8c4.png">

Subject-verb agreement

<img width="766" alt="Screenshot 2022-03-30 at 2 18 40 PM" src="https://user-images.githubusercontent.com/97666199/160764296-2d31c7a1-8f44-4630-8e0d-18ae70e02b2e.png">

Password does not meet requirements?

**Comment by clement0010** [comment]
I take this as an UI bug then?

**Comment by sibinhho99-nus** [comment]
Yes, error message does not match the error is considered a functionality bug as in https://nus-cs2103-ay2122s2.github.io/website/admin/tp-pe.html#pe-phase-1-bug-reporting-2
