### ISSUE TITLE
Cards have fields cut-off after one line

### ISSUE THREAD

**Issue by juslam19** [AY2122S2-CS2103T-T11-1/tp#122]
The user is shown a single line that is truncated when the content is too long to accomodate on a single line, with the current window width. 

### To replicate:

1. Make a field in an add command obscenely long. This applies for all types.
2. `add i/S1234569L t/consultation dt/19-09-2020 tm/19-00 dg/Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate eu scelerisque felis imperdiet. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Pellentesque elit ullamcorper dignissim cras. Quis viverra nibh cras pulvinar. Amet dictum sit amet justo donec enim diam. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Ut placerat orci nulla pellentesque. At quis risus sed vulputate odio. Sit amet est placerat in egestas erat. Faucibus ornare suspendisse sed nisi lacus sed. Integer malesuada nunc vel risus commodo. Nunc congue nisi vitae suscipit tellus mauris a diam. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. fe/54.00 nt/Should get more cough drops.`

![image](https://user-images.githubusercontent.com/77272958/160784232-15aa689a-377c-4783-8f28-5c50a12411f4.png)

### Intended Result:

User is to see content in each Label in the Card that, if it has content over a line's length, to wrap the text to the next line and so forth, thus displaying content in its entirety in multiple lines. This is supposed to occur for all the Labels all types of cards. 

### Failed Attempts:
- adding to Label `wrapText="true"` to the fxml file (w and w/o `prefWidth="some number"`)
- adding to `@FXML Label windowBox.setWrapText(true)` in the java file (w and w/o `windowBox.setPrefWidth(some number)`)

### IMPORTANT NOTE: I have not included my modifications as they do not work.

**Comment by clement0010** [comment]
Manage to get it working. Remove all `prefHeight` and `prefWidth`. 
![image](https://user-images.githubusercontent.com/56408987/160808331-c20cafb3-8bf2-41d2-ab0c-75ecf014b807.png)


Unless needed try not to use them cus as it will truncate cards & panel as well. Best to use `minWidth` and `minHeight` for responsive display.

The use of `Region` is also redundant

**Comment by clement0010** [comment]
fyi, i'll help fix this

**Comment by juslam19** [comment]
Thank you!
