### ISSUE TITLE
[PE-D] Only showing Patient's NRIC in Medical Information is not user friendly for viewing

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-1/tp#190]
When we view the patient's medical info, we want to see the related patient's personal info also like name to be user friendly, or else the feature would not be optimized for target doctors to view certain medical report

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: HanJiyao/ped#10

**Comment by sibinhho99-nus** [comment]
Same as #163
