### ISSUE TITLE
[PE-D] Inconsistent of Date format for Consultation Information and Test Result

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-1/tp#201]
One is DD-MM-YYY one is YYYY-MM-DD this may confusing user

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: HanJiyao/ped#19

**Comment by joey-chance** [comment]
@juslam19 Can you standardize it to YYYY-MM-DD?

**Comment by juslam19** [comment]
DONE
