### ISSUE TITLE
As a user, I can view the patient's health summary

### ISSUE THREAD

**Issue by clement0010** [AY2122S2-CS2103T-T11-1/tp#71]
so that I can stay updated on the patient's current health status.

**Comment by sibinhho99-nus** [comment]
Leave to v1.3b

**Comment by sibinhho99-nus** [comment]
Leave to v1.3b

**Comment by clement0010** [comment]
> Leave to v1.3b

@cheekean5848 assigned this to himself 2 days ago. Do u want to communicate with him who will be doing it?

**Comment by sibinhho99-nus** [comment]
> > Leave to v1.3b
> 
> @cheekean5848 assigned this to himself 2 days ago. Do u want to communicate with him who will be doing it?

yup will do in team meeting. we should discuss the implementation further. I'm not sure if we should have one person working on the entire summary page, each person doing a part in the summary dashboard for their entity type (Patient, Medical, Prescription etc), or sth else
